const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    year: 1925,
    available: true,
    image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
    description: "A critique of the American Dream set in the Roaring Twenties, following the mysterious millionaire Jay Gatsby and his obsession with Daisy Buchanan.",
    rating: 4.4,
    pages: 180,
    language: "English",
    publisher: "Scribner",
    isbn: "9780743273565"
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    year: 1949,
    available: false,
    image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
    description: "A chilling vision of a totalitarian future where surveillance and propaganda dominate every aspect of life.",
    rating: 4.7,
    pages: 328,
    language: "English",
    publisher: "Secker & Warburg",
    isbn: "9780451524935"
  },
  {
    id: 3,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Historical Fiction",
    year: 1960,
    available: true,
    image: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
    description: "A powerful story of racial injustice and moral growth seen through the eyes of young Scout Finch in the segregated American South.",
    rating: 4.8,
    pages: 281,
    language: "English",
    publisher: "J.B. Lippincott & Co.",
    isbn: "9780061120084"
  },
  {
    id: 4,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    genre: "Non-Fiction",
    year: 2011,
    available: true,
    image: "https://covers.openlibrary.org/b/id/8370226-L.jpg",
    description: "A sweeping history of humankind from the Stone Age to the modern age, exploring how Homo sapiens came to dominate the Earth.",
    rating: 4.6,
    pages: 443,
    language: "English",
    publisher: "Harvill Secker",
    isbn: "9780062316097"
  },
  {
    id: 5,
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    year: 1932,
    available: false,
    image: "https://covers.openlibrary.org/b/id/8306663-L.jpg",
    description: "A satirical vision of a future society driven by technology, consumerism, and state control.",
    rating: 4.2,
    pages: 268,
    language: "English",
    publisher: "Chatto & Windus",
    isbn: "9780060850524"
  },
  {
    id: 6,
    title: "Moby-Dick",
    author: "Herman Melville",
    genre: "Adventure",
    year: 1851,
    available: true,
    image: "https://covers.openlibrary.org/b/id/5552221-L.jpg",
    description: "Captain Ahab’s obsessive quest to kill the great white whale becomes a powerful allegory about vengeance, fate, and humanity.",
    rating: 4.0,
    pages: 635,
    language: "English",
    publisher: "Harper & Brothers",
    isbn: "9781503280786"
  },
  {
    id: 7,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    year: 1813,
    available: true,
    image: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
    description: "A witty romantic comedy about manners, class, and love centered around the strong-minded Elizabeth Bennet and proud Mr. Darcy.",
    rating: 4.5,
    pages: 279,
    language: "English",
    publisher: "T. Egerton",
    isbn: "9780141439518"
  },
  {
    id: 8,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Classic",
    year: 1951,
    available: true,
    image: "https://covers.openlibrary.org/b/id/8221251-L.jpg",
    description: "A raw and honest coming-of-age story of teenage alienation and loss told by the cynical Holden Caulfield.",
    rating: 4.0,
    pages: 214,
    language: "English",
    publisher: "Little, Brown and Company",
    isbn: "9780316769488"
  },
  {
    id: 9,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: 1937,
    available: true,
    image: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
    description: "Bilbo Baggins embarks on an epic adventure with dwarves to reclaim treasure from a dragon in this charming prelude to The Lord of the Rings.",
    rating: 4.7,
    pages: 310,
    language: "English",
    publisher: "George Allen & Unwin",
    isbn: "9780547928227"
  },
  {
    id: 10,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: 1954,
    available: false,
    image: "https://covers.openlibrary.org/b/id/8135410-L.jpg",
    description: "An epic fantasy of good versus evil as Frodo and the Fellowship seek to destroy a powerful ring and save Middle-earth.",
    rating: 4.9,
    pages: 1178,
    language: "English",
    publisher: "George Allen & Unwin",
    isbn: "9780618640157"
  },
  {
    id: 11,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Adventure",
    year: 1988,
    available: true,
    image: "https://covers.openlibrary.org/b/id/8167892-L.jpg",
    description: "A philosophical tale about following one's dreams through the story of a young shepherd named Santiago.",
    rating: 4.3,
    pages: 208,
    language: "English",
    publisher: "HarperOne",
    isbn: "9780061122415"
  },
  {
    id: 12,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    genre: "Psychological Fiction",
    year: 1866,
    available: false,
    image: "https://covers.openlibrary.org/b/id/8231857-L.jpg",
    description: "A psychological exploration of morality and redemption through the story of a young man's crime and consequences.",
    rating: 4.6,
    pages: 671,
    language: "English",
    publisher: "The Russian Messenger",
    isbn: "9780140449136"
  },
  {
    id: 13,
    title: "The Book Thief",
    author: "Markus Zusak",
    genre: "Historical Fiction",
    year: 2005,
    available: true,
    image: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    description: "A story narrated by Death, chronicling the life of a young girl in Nazi Germany who finds solace in stealing books.",
    rating: 4.5,
    pages: 552,
    language: "English",
    publisher: "Picador",
    isbn: "9780375842207"
  },
  {
    id: 14,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    genre: "Dystopian",
    year: 1953,
    available: true,
    image: "https://covers.openlibrary.org/b/id/8225230-L.jpg",
    description: "In a society where books are banned and burned, a fireman begins to question everything he believes.",
    rating: 4.3,
    pages: 194,
    language: "English",
    publisher: "Ballantine Books",
    isbn: "9781451673319"
  },
  {
    id: 15,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    genre: "Gothic Fiction",
    year: 1847,
    available: false,
    image: "https://covers.openlibrary.org/b/id/8221460-L.jpg",
    description: "An orphan girl's growth into adulthood and her love for the brooding Mr. Rochester.",
    rating: 4.4,
    pages: 532,
    language: "English",
    publisher: "Smith, Elder & Co.",
    isbn: "9780141441146"
  },
  {
    id: 16,
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    genre: "Drama",
    year: 2003,
    available: true,
    image: "https://covers.openlibrary.org/b/id/8225694-L.jpg",
    description: "A story of friendship and betrayal between two boys growing up in Kabul, Afghanistan.",
    rating: 4.5,
    pages: 371,
    language: "English",
    publisher: "Riverhead Books",
    isbn: "9781594631931"
  },
  {
    id: 17,
    title: "Life of Pi",
    author: "Yann Martel",
    genre: "Adventure",
    year: 2001,
    available: true,
    image: "https://covers.openlibrary.org/b/id/8313796-L.jpg",
    description: "A young boy survives a shipwreck and shares a lifeboat with a Bengal tiger.",
    rating: 4.3,
    pages: 319,
    language: "English",
    publisher: "Knopf Canada",
    isbn: "9780156027328"
  },
  {
    id: 18,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    genre: "Gothic Fiction",
    year: 1847,
    available: false,
    image: "https://covers.openlibrary.org/b/id/8232004-L.jpg",
    description: "A tale of passion and revenge on the Yorkshire moors.",
    rating: 4.1,
    pages: 416,
    language: "English",
    publisher: "Thomas Cautley Newby",
    isbn: "9780141439556"
  },
  {
    id: 19,
    title: "The Road",
    author: "Cormac McCarthy",
    genre: "Post-Apocalyptic",
    year: 2006,
    available: true,
    image: "https://covers.openlibrary.org/b/id/8235701-L.jpg",
    description: "A father and son journey through a bleak, burned America, searching for hope.",
    rating: 4.2,
    pages: 287,
    language: "English",
    publisher: "Alfred A. Knopf",
    isbn: "9780307387899"
  },
  {
    id: 20,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    genre: "Philosophical Fiction",
    year: 1890,
    available: true,
    image: "https://covers.openlibrary.org/b/id/8235886-L.jpg",
    description: "A man sells his soul for eternal youth and beauty, while his portrait ages in his place.",
    rating: 4.4,
    pages: 254,
    language: "English",
    publisher: "Lippincott's Monthly Magazine",
    isbn: "9780141439570"
  }
];

export default books;
